name: 🐞 Issue Report
description: Report a issue in WVTonSubjects
labels: [bug]
body:

  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce
      description: Provide an example of the issue.
      placeholder: |
        Example:
          1. First step
          2. Second step
          3. Issue here
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      placeholder: |
        Example:
          "This should happen..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      placeholder: |
        Example:
          "This happened instead..."
    validations:
      required: true

  - type: input
    id: WVTonSubjects-version
    attributes:
      label: WVTonSubjects version
      description: |
        You can find your WVTonSubjects version in **Settings**.
      placeholder: |
        Example: "0.2.6"
=======
ame: ⭐ Feature request
description: Suggest a feature to improve the app
labels: [enhancement]
body:

  - type: textarea
    id: feature-description
    attributes:
      label: Describe your suggested feature
      description: How can an existing source be improved?
      placeholder: |
        Example:
          "It should work like this..."
          